### ISSUE TITLE
Planes Collection

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/nutshell-alces#4]
# User Stories
- [x] As a user, I should be able to view all the planes PanAm owns.
- [x] As a user, I should be able to create a new plane.
- [x] As a user, I should be able to edit a plane.
- [x] As a user, I should be able to delete a plane.

# AC
**WHEN** I click on the "Planes" button on the navbar
**THEN** I shall view all stationed planes at the airport by Name, Type of Plane, and Last Serviced.
**AND** I should see an add, delete, and edit button on each card and the ability to add a new plane, delete a plane from the airport, and edit a plane's name and type.

# Dev Notes
- [x] "Airplanes" header will be an h1.
- [x] Bootstrap cards will be used on domString.
- [x] planes.json, planesData.js, planesList.js, planes.js
- [x] Images & plane descriptions will be imported through axios/firebase. => axios.get(`${baseUrl}
- [x] (Add) class="fas fa-plus-square" style="color:#2767AD => axios.post(`${baseUrl}
- [x] (Delete) class="fas fa-trash" style="color:#2767AD => axios.delete(`${baseUrl}
- [x] (Edit) class="far fa-edit" style="color:#2767AD => axios.put(`${baseUrl}
- [ ] Last serviced will use a timestamp that will be a footer on each card.

**Comment by MarkyAaronYoung** [comment]
<img width="580" alt="AirplanesPage" src="https://user-images.githubusercontent.com/62973018/87471778-869ef080-c5e4-11ea-8424-24d216017974.png">

**Comment by luketlancaster** [comment]
let's have a bit more detail about how you're going to display this content. Is it a bulleted list? An `<h2>` somewhere? Just a little closer to actual layout would be 💯

**Comment by psihanorak** [comment]
See User Stories and Dev Notes.
