### ISSUE TITLE
Create New Flight

### ISSUE THREAD

**Issue by jeaninedavis** [nss-evening-cohort-12/nutshell-alces#58]
# User Story
As a user, I should be able to create a new flight.

# AC
**WHEN** a User goes presses Create Flight they should see a form for adding a flight
**THEN** they should see categories to add to the flight
**AND** a button to add it to the flights at the bottom

# Dev Notes
* create a `flightDashboard` folder
* create 
```html
<div id="flightDashboardContainer>
    <form id="flightDashboardForm"> @luketlancaster for some reason I feel like the quadforms need to be in a big form?
<button class= "btn btn-primary" id="submitFlight"><button>
    </form>
</div> 
```
### The flight quadrants are broken up below
- [ ] Create Flight (crew) Flight Attendant Div (#78 )
- [ ] Create Flight (crew) Pilots Div (#77 )
- [ ] Create Flight Destination Div. (#71 )
- [ ] Create Flight Plane Div (#76 )

<img width="686" alt="Screen Shot 2020-07-23 at 6 50 16 PM" src="https://user-images.githubusercontent.com/62917622/88350209-0b41eb00-cd18-11ea-93f7-ab3652681929.png">

**Comment by luketlancaster** [comment]
I think you’ll want each of those quadrants to be it’s own component, and the one component builds them all together

**Comment by jamalbrowning** [comment]
@luketlancaster i struggled with this. but it did make sense kinda in my head. let me know whatchya think palihug (filipino for please)

**Comment by luketlancaster** [comment]
1. So you don't *technically* need a form at all for any of this...you could use divs with various input types
2. I would separate each of these code bits into their own cards, and each of you can work on each of them semi-independently from each other (once you have the basic container already in there)

The way I conceptualize this is it's almost like it's own whole new app. It's almost as complex as everything else that's been done thus far on this project, so you can treat it as such: many cards, everyone gets part of the project to work on, etc. 

Overall this is a **really** good start at breaking it up.

oh, sidenote, for Pilots and Flight Attendants you *could* use firebase query rules to fetch only those types (I don't remember what properties are on your crew members). So do your orderBy/equalTo and add your db rules and whatnot...
